//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubItem
    {
        public int SubItemID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SubItemDesc { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
